-- 기존 데이터 삭제
DELETE FROM attendance_records;
DELETE FROM members;
DELETE FROM discipleship_classes;

-- 제자반 생성
INSERT INTO discipleship_classes (name, is_active) VALUES ('양선반', true);
INSERT INTO discipleship_classes (name, is_active) VALUES ('온유반', true);
INSERT INTO discipleship_classes (name, is_active) VALUES ('인내절제반', true);
INSERT INTO discipleship_classes (name, is_active) VALUES ('화평반', true);
INSERT INTO discipleship_classes (name, is_active) VALUES ('충성희락반', true);
INSERT INTO discipleship_classes (name, is_active) VALUES ('사랑반', true);

-- 회원 등록
DO $$ DECLARE
  cls_양선반 UUID;
  cls_온유반 UUID;
  cls_인내절제반 UUID;
  cls_화평반 UUID;
  cls_충성희락반 UUID;
  cls_사랑반 UUID;
BEGIN
  SELECT id INTO cls_양선반 FROM discipleship_classes WHERE name = '양선반';
  SELECT id INTO cls_온유반 FROM discipleship_classes WHERE name = '온유반';
  SELECT id INTO cls_인내절제반 FROM discipleship_classes WHERE name = '인내절제반';
  SELECT id INTO cls_화평반 FROM discipleship_classes WHERE name = '화평반';
  SELECT id INTO cls_충성희락반 FROM discipleship_classes WHERE name = '충성희락반';
  SELECT id INTO cls_사랑반 FROM discipleship_classes WHERE name = '사랑반';

  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('이진영', '01092947697', '강사', NULL, false, cls_양선반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('우유정', '01043316847', '강사', '2000-08-12', false, cls_온유반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('손요한', '01088277029', '목사', '2000-04-19', false, cls_인내절제반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('최상현', '01084421951', '강사', '2000-11-22', true, cls_화평반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('김진영', '01084184568', '강사', '2000-08-11', true, cls_충성희락반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('김은영', '01045889100', '강사', '2000-09-28', false, cls_사랑반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('강서연', NULL, NULL, '2000-04-13', false, cls_양선반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('강우진', NULL, NULL, '2000-02-16', false, cls_충성희락반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('강하영', NULL, NULL, '2000-10-08', false, cls_인내절제반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('구은미', NULL, NULL, '2000-02-09', false, cls_온유반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('김나현', NULL, NULL, '2000-01-08', false, cls_양선반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('김성훈', NULL, NULL, '2000-07-20', false, cls_화평반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('김수빈', NULL, NULL, '2000-01-15', false, cls_양선반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('김영웅', NULL, NULL, '2000-03-01', false, cls_인내절제반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('김이진', NULL, NULL, '2000-02-12', false, cls_인내절제반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('김지윤', NULL, NULL, '2000-07-05', false, cls_충성희락반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('김진호', NULL, NULL, '2000-10-02', false, cls_인내절제반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('김하람', NULL, NULL, '2000-03-18', false, cls_인내절제반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('김혜진', NULL, NULL, '2000-11-09', false, cls_화평반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('남진관', NULL, NULL, '2000-09-08', false, cls_화평반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('라안나', NULL, NULL, '2000-09-23', false, cls_양선반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('문우식', NULL, NULL, '2000-10-16', false, cls_화평반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('민서희', NULL, NULL, '2000-05-21', false, cls_충성희락반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('민시온', NULL, NULL, '2000-10-20', false, cls_충성희락반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('민주희', NULL, NULL, '2000-11-05', false, cls_온유반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('박라아', NULL, NULL, '2000-08-30', false, cls_양선반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('박서연', NULL, NULL, '2000-10-30', false, cls_충성희락반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('박승협', NULL, NULL, '2000-02-08', false, cls_사랑반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('박시혁', NULL, NULL, '2000-10-22', false, cls_양선반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('박이레', NULL, NULL, '2000-01-16', false, cls_충성희락반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('박종혁', NULL, NULL, NULL, false, cls_화평반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('박주용', NULL, NULL, '2000-02-03', false, cls_인내절제반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('박지호', NULL, NULL, '2000-10-22', false, cls_인내절제반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('박호진', NULL, NULL, '2000-01-01', false, cls_사랑반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('방진경', NULL, NULL, NULL, false, cls_온유반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('손찬송', NULL, NULL, NULL, false, cls_온유반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('송대희', NULL, NULL, '2000-11-24', false, cls_화평반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('신민철', NULL, NULL, '2000-07-28', false, cls_양선반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('신정문', NULL, NULL, '2000-10-09', false, cls_온유반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('신정수', NULL, NULL, '2000-06-25', false, cls_온유반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('안시온', NULL, NULL, '2000-10-19', false, cls_양선반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('양주영', NULL, NULL, '2000-06-03', false, cls_인내절제반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('엄유빈', NULL, NULL, '2000-11-11', false, cls_인내절제반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('위시원', NULL, NULL, '2000-08-21', false, cls_온유반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('유서영', NULL, NULL, '2000-01-26', false, cls_양선반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('유은선', NULL, NULL, '2000-02-26', false, cls_충성희락반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('유준영', NULL, NULL, NULL, false, cls_충성희락반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('유지성', NULL, NULL, '2000-02-14', false, cls_충성희락반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('유지환', NULL, NULL, '2000-05-01', false, cls_양선반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('윤소망', NULL, NULL, '2000-02-17', false, cls_사랑반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('이승수', NULL, NULL, NULL, false, cls_인내절제반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('이영민', NULL, NULL, NULL, false, cls_인내절제반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('이예린', NULL, NULL, '2000-04-30', false, cls_인내절제반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('이지민', NULL, NULL, '2000-08-29', false, cls_충성희락반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('이지원', NULL, NULL, '2000-09-13', false, cls_충성희락반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('이지원2', NULL, NULL, NULL, false, cls_화평반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('이화진', NULL, NULL, '2000-04-01', false, cls_온유반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('임동윤', NULL, NULL, '2000-11-20', false, cls_사랑반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('임동하', NULL, NULL, '2000-01-12', false, cls_양선반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('정마이샤', NULL, NULL, '2000-07-29', false, cls_충성희락반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('정예은', NULL, NULL, '2000-08-14', false, cls_충성희락반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('정찬우', NULL, NULL, '2000-11-30', false, cls_인내절제반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('조세희', NULL, NULL, '2000-11-30', false, cls_사랑반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('조영걸', NULL, NULL, '2000-05-05', false, cls_화평반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('조혜륜', NULL, NULL, '2000-01-24', false, cls_양선반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('주현규', NULL, NULL, '2000-08-06', false, cls_충성희락반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('최준구', NULL, NULL, '2000-02-26', false, cls_사랑반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('추승엽', NULL, NULL, '2000-05-14', false, cls_화평반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('피두헌', NULL, NULL, '2000-03-19', false, cls_사랑반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('피민서', NULL, NULL, '2000-06-07', false, cls_양선반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('한인애', NULL, NULL, '2000-11-26', false, cls_양선반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('허은혜', NULL, NULL, '2000-03-17', false, cls_온유반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('허지영', NULL, NULL, '2000-07-18', false, cls_온유반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('이형인', NULL, '전도사', '2000-06-22', false, NULL, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('강하은', NULL, NULL, '2000-12-07', false, NULL, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('박현준', NULL, NULL, '2000-09-03', false, NULL, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('이석현', NULL, NULL, '2000-11-20', false, NULL, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('이성현', NULL, NULL, '2000-09-21', false, NULL, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('위승혁', NULL, NULL, '2000-11-09', false, NULL, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('신우철', NULL, NULL, '2000-01-13', false, NULL, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('김현수', NULL, NULL, '2000-02-16', false, cls_충성희락반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('박서아', NULL, NULL, '2000-05-11', false, cls_온유반, true);
  INSERT INTO members (name, phone, title, date_of_birth, is_lunar_birthday, class_id, is_active) VALUES ('이예지', NULL, NULL, '2000-11-01', false, NULL, true);
END $$;
